/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LogRouteImport } from './routes/log'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as AdSbRouteImport } from './routes/ad-sb'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as CpdRouteImport } from './routes/cpd'
import { Route as TypeRatingsRouteImport } from './routes/type-ratings'
import { Route as JobsRouteImport } from './routes/jobs'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AdSbRoute = AdSbRouteImport.update({
  id: '/ad-sb',
  path: '/ad-sb',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CpdRoute = CpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeRatingsRoute = TypeRatingsRouteImport.update({
  id: '/type-ratings',
  path: '/type-ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/experience': typeof ExperienceRoute
  '/log': typeof LogRoute
  '/logs': typeof LogsRoute
  '/readiness': typeof ReadinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/components': typeof ComponentsRoute
  '/ad-sb': typeof AdSbRoute
  '/tools': typeof ToolsRoute
  '/cpd': typeof CpdRoute
  '/type-ratings': typeof TypeRatingsRoute
  '/jobs': typeof JobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/experience': typeof ExperienceRoute
  '/log': typeof LogRoute
  '/logs': typeof LogsRoute
  '/readiness': typeof ReadinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/components': typeof ComponentsRoute
  '/ad-sb': typeof AdSbRoute
  '/tools': typeof ToolsRoute
  '/cpd': typeof CpdRoute
  '/type-ratings': typeof TypeRatingsRoute
  '/jobs': typeof JobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/experience': typeof ExperienceRoute
  '/log': typeof LogRoute
  '/logs': typeof LogsRoute
  '/readiness': typeof ReadinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/components': typeof ComponentsRoute
  '/ad-sb': typeof AdSbRoute
  '/tools': typeof ToolsRoute
  '/cpd': typeof CpdRoute
  '/type-ratings': typeof TypeRatingsRoute
  '/jobs': typeof JobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/experience'
    | '/log'
    | '/logs'
    | '/readiness'
    | '/reset-password'
    | '/search'
    | '/components'
    | '/ad-sb'
    | '/tools'
    | '/cpd'
    | '/type-ratings'
    | '/jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/experience'
    | '/log'
    | '/logs'
    | '/readiness'
    | '/reset-password'
    | '/search'
    | '/components'
    | '/ad-sb'
    | '/tools'
    | '/cpd'
    | '/type-ratings'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/experience'
    | '/log'
    | '/logs'
    | '/readiness'
    | '/reset-password'
    | '/search'
    | '/components'
    | '/ad-sb'
    | '/tools'
    | '/cpd'
    | '/type-ratings'
    | '/jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ExperienceRoute: typeof ExperienceRoute
  LogRoute: typeof LogRoute
  LogsRoute: typeof LogsRoute
  ReadinessRoute: typeof ReadinessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ComponentsRoute: typeof ComponentsRoute
  AdSbRoute: typeof AdSbRoute
  ToolsRoute: typeof ToolsRoute
  CpdRoute: typeof CpdRoute
  TypeRatingsRoute: typeof TypeRatingsRoute
  JobsRoute: typeof JobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-sb': {
      id: '/ad-sb'
      path: '/ad-sb'
      fullPath: '/ad-sb'
      preLoaderRoute: typeof AdSbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpd': {
      id: '/cpd'
      path: '/cpd'
      fullPath: '/cpd'
      preLoaderRoute: typeof CpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type-ratings': {
      id: '/type-ratings'
      path: '/type-ratings'
      fullPath: '/type-ratings'
      preLoaderRoute: typeof TypeRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ExperienceRoute: ExperienceRoute,
  LogRoute: LogRoute,
  LogsRoute: LogsRoute,
  ReadinessRoute: ReadinessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ComponentsRoute: ComponentsRoute,
  AdSbRoute: AdSbRoute,
  ToolsRoute: ToolsRoute,
  CpdRoute: CpdRoute,
  TypeRatingsRoute: TypeRatingsRoute,
  JobsRoute: JobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
